apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-monitoring
  namespace: argocd
spec:
  project: default
  source:
    chart: kube-prometheus-stack
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 58.x.x
    helm:
      values: |
        grafana:
          adminPassword: "admin"
          service:
            type: NodePort
            nodePort: 32000
        prometheus:
          prometheusSpec:
            # ЭТИ ДВЕ СТРОКИ ЗАСТАВЯТ ПРОМЕТЕУС ВИДЕТЬ ВСЕ МОНИТОРЫ БЕЗ ИСКЛЮЧЕНИЯ:
            serviceMonitorSelectorNilUsesHelmValues: false
            podMonitorSelectorNilUsesHelmValues: false
        kubelet:
          enabled: true
          serviceMonitor:
            https: false
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
